# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
#
# Attila Siposs <sipiatti@gmail.com>, 2010, 2011.
# Siposs Attila <siposs.attila@isd-dunaferr.hu>, 2010.
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-04-05 17:38+0300\n"
"PO-Revision-Date: 2011-01-20 15:06+0100\n"
"Last-Translator: Attila Siposs <sipiatti@gmail.com>\n"
"Language-Team: Hungarian <pardus-translators@pardus.org.tr>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Generator: Lokalize 1.0\n"

#: gui/ScrInstall.py:161
#, python-format
msgid "Installing <b>%(name)s</b> -- %(summary)s"
msgstr "Telepítés: <b>%(name)s</b> -- %(summary)s"

#: gui/ScrInstall.py:170
#, python-format
msgid "Configuring <b>%s</b>"
msgstr "Beállítás: <b>%s</b>"

#: gui/ScrInstall.py:195 gui/ScrPartitionAuto.py:44
#: gui/ScrPartitionManual.py:138 gui/ScrCheckCD.py:96 gui/YaliWindow.py:212
#: gui/YaliWindow.py:217 gui/YaliWindow.py:222
msgid "Warning"
msgstr "Figyelem"

#: gui/ScrInstall.py:196
#, fuzzy, python-format
msgid ""
"Following error occured while installing packages:<b>%s</b><br><br>Do you "
"want to retry?"
msgstr ""
"A csomagok telepítésekor az alábbi hibák léptek fel:\n"
"<b>%s</b>"

#: gui/ScrInstall.py:202 gui/YaliDialog.py:218 gui/YaliDialog.py:234
#: gui/ScrSummary.py:297 storage/storageBackendHelpers.py:233
#: storage/storageBackendHelpers.py:254 storage/storageBackendHelpers.py:304
msgid "Yes"
msgstr "Igen"

#: gui/ScrInstall.py:202 gui/YaliDialog.py:220 gui/YaliDialog.py:235
#: gui/ScrSummary.py:297 storage/storageBackendHelpers.py:233
#: storage/storageBackendHelpers.py:254 storage/storageBackendHelpers.py:304
msgid "No"
msgstr "Nem"

#: gui/ScrInstall.py:258
#, python-format
msgid ""
"An error occured during the installation of packages.\n"
"This may be caused by a corrupted installation medium error:\n"
"%s\n"
msgstr ""
"A csomagok telepítésekor hiba lépett fel.\n"
"Ezt okozhatja a telepítő adathordozó sérülése.\n"
"%s\n"

#: gui/runner.py:117
msgid "Error!"
msgstr "Hiba!"

#: gui/runner.py:118
#, python-format
msgid ""
"An error occurred when attempting to load an installer interface component.\n"
"\n"
"className = %s.Widget"
msgstr ""
"Hiba történt az egyik interfész komponens betöltése közben.\n"
"\n"
"className = %s.Widget"

#: gui/runner.py:122 gui/ScrRescuePassword.py:123 gui/ScrRescue.py:95
#: gui/YaliWindow.py:385 storage/storageset.py:388
msgid "Exit"
msgstr "Kilépés"

#: gui/runner.py:122
msgid "Retry"
msgstr "Újra"

#: gui/ScrPartitionAuto.py:45
#, python-format
msgid ""
"No partitions are available to resize. Only physical\n"
"partitions which size is greater than %s MB can be resized."
msgstr ""
"Nincs átméretezhető partíció. Csak %s MB-nál nagyobb\n"
"fizikai partíciók méretezhetók át."

#: gui/ScrPartitionAuto.py:60
#, fuzzy
msgid "Use All Disks"
msgstr "Teljes terület használata"

#: gui/ScrKeyboard.py:73
msgid "Use Alt-Shift to toggle between alternative keyboard layouts"
msgstr ""
"Használja az Alt-Shift kombinációt az alternatív kiosztások közti váltáshoz"

#: gui/ScrPartitionManual.py:94
#, fuzzy, python-format
msgid ""
"The partitioning scheme you requested caused the following critical errors."
"You must correct these errors before you continue your installation of %s."
msgstr ""
"A választott partícionálási séma kritikus\n"
"hibákat eredményezett.\n"
"Ki kell javítani a hibákat a %s telepítésének\n"
"folytatásához."

#: gui/ScrPartitionManual.py:101
msgid "Partitioning Errors"
msgstr "Partícionálási hibák"

#: gui/ScrPartitionManual.py:106
#, fuzzy
msgid ""
"The partitioning scheme you requested generated the following warnings. "
"Would you like to continue with your requested partitioning scheme?"
msgstr ""
"A választott partícionálási séma az alábbi figyelmeztetéseket\n"
"generálta. Folytatni akarja?"

#: gui/ScrPartitionManual.py:112
msgid "Partitioning Warnings"
msgstr "Figyelmeztető üzenetek partícionáláskor"

#: gui/ScrPartitionManual.py:114 gui/ScrPartitionManual.py:140
#: gui/YaliDialog.py:218 storage/__init__.py:164
msgid "Ok"
msgstr "Ok"

#: gui/ScrPartitionManual.py:114 gui/ScrPartitionManual.py:130
#: gui/ScrPartitionManual.py:140 gui/YaliDialog.py:220
#: gui/Ui/partitionshrinkwidget.py:103 gui/Ui/partresize.py:103
#: gui/Ui/setupuserswidget.py:513 gui/lvm_gui.py:418 gui/lvm_gui.py:465
#: gui/lvm_gui.py:552 storage/storageBackendHelpers.py:92
#: storage/storageBackendHelpers.py:296 storage/__init__.py:930
msgid "Cancel"
msgstr "Mégsem"

#: gui/ScrPartitionManual.py:120
#, fuzzy
msgid ""
"The following pre-existing devices have been selected to be formatted, "
"destroying all data."
msgstr ""
"Az alábbi eszközök lettek megjelölve formázásra,\n"
"minden adat törlődni fog róluk."

#: gui/ScrPartitionManual.py:128
msgid "Format Warnings"
msgstr "Formázási figyelmeztetés"

#: gui/ScrPartitionManual.py:130 gui/Ui/manualpartwidget.py:197
#: gui/Ui/raid.py:117 gui/Ui/partition.py:157 gui/Ui/logicalvolume.py:159
#: storage/storageset.py:387
msgid "Format"
msgstr "Formázás"

#: gui/ScrPartitionManual.py:138
msgid "All Changes that you made will be removed"
msgstr "Minden eddigi változtatás el lesz távolítva."

#: gui/ScrPartitionManual.py:148
msgid "Standard"
msgstr "Szabványos"

#: gui/ScrPartitionManual.py:149
msgid "LVM"
msgstr "LVM"

#: gui/ScrPartitionManual.py:150
msgid "RAID"
msgstr "RAID"

#: gui/ScrPartitionManual.py:152
msgid "Partition"
msgstr "Partíció"

#: gui/ScrPartitionManual.py:153 gui/Ui/createdevicewidget.py:144
msgid "General purpose of partition creation"
msgstr "A partícionálás alapvető célja"

#: gui/ScrPartitionManual.py:155 gui/Ui/createdevicewidget.py:149
msgid "Physical Volume"
msgstr "Fizikai kötet"

#: gui/ScrPartitionManual.py:156 gui/Ui/createdevicewidget.py:150
msgid "Create LVM formatted partition"
msgstr "LVM partíció létrehozása"

#: gui/ScrPartitionManual.py:158 gui/Ui/createdevicewidget.py:145
msgid "Volume Group"
msgstr "VG"

#: gui/ScrPartitionManual.py:159 gui/Ui/createdevicewidget.py:146
msgid "Requires at least 1 free LVM formatted partition"
msgstr "Legalább egy szabad LVM formázott partíció szükséges"

#: gui/ScrPartitionManual.py:161 gui/Ui/createdevicewidget.py:147
msgid "Logical Volume"
msgstr "Logikai kötet (LV)"

#: gui/ScrPartitionManual.py:162 gui/Ui/createdevicewidget.py:148
msgid "Create Logical Volume on selected Volume Group"
msgstr "Logikai kötet létrehozása a kiválasztott VG-n"

#: gui/ScrPartitionManual.py:164
msgid "Member"
msgstr "Tag"

#: gui/ScrPartitionManual.py:165 gui/Ui/createdevicewidget.py:152
msgid "Create Raid formatted partition"
msgstr "Raid partíció létrehozása"

#: gui/ScrPartitionManual.py:167
msgid "Array"
msgstr "Tömb"

#: gui/ScrPartitionManual.py:168 gui/Ui/createdevicewidget.py:154
msgid "Requires at least 2 free Raid formatted partition"
msgstr "Legalább két Raid partíció szükséges"

#: gui/ScrPartitionManual.py:231
msgid "Volume Groups"
msgstr "VG"

#: gui/ScrPartitionManual.py:244 gui/ScrPartitionManual.py:320
msgid "Free"
msgstr "Szabad"

#: gui/ScrPartitionManual.py:253
msgid "Raid Arrays"
msgstr "RAID tömb"

#: gui/ScrPartitionManual.py:268
msgid "Hard Drives"
msgstr "Merevlemez"

#: gui/ScrPartitionManual.py:297
msgid "Can't handle more than one extended partition per disk"
msgstr "Nem kezelhető egynél több kiterjesztett partíció lemezenként"

#: gui/ScrPartitionManual.py:304
msgid "Crossed logical partition before extended"
msgstr "Keresztezett logikai partíció a kiterjesztés előtt"

#: gui/ScrPartitionManual.py:325
msgid "Extended"
msgstr "Kiterjesztett"

#: gui/ScrPartitionManual.py:351 storage/partitioning.py:1648
#: storage/partitioning.py:1680
msgid "Error Partitioning"
msgstr "Partícionálási hiba"

#: gui/ScrPartitionManual.py:352
#, python-format
msgid "Could not allocate requested partitions: %s."
msgstr "Ez a partíció nem beállítható: %s."

#: gui/ScrPartitionManual.py:356
msgid "Warning Partitioning"
msgstr "Partícionálási figyelmeztetés"

#: gui/ScrPartitionManual.py:357
#, python-format
msgid "Warning: %s."
msgstr "Figyelmeztetés: %s."

#: gui/ScrPartitionManual.py:358 storage/storageBackendHelpers.py:319
msgid "Modify Partition"
msgstr "Partíció módosítása"

#: gui/ScrPartitionManual.py:358 gui/ScrRescuePassword.py:123
#: gui/ScrRescue.py:95 gui/lvm_gui.py:418 gui/lvm_gui.py:465
#: storage/storageset.py:336
msgid "Continue"
msgstr "Folytatás"

#: gui/ScrPartitionManual.py:472
msgid "Partition Selection Warning"
msgstr "Partíció kiválasztási figyelmeztetés"

#: gui/ScrPartitionManual.py:473
msgid "Please select free physical partition to create new device."
msgstr "Új eszköz létrehozásához válasszon egy szabad fizikai partíciót."

#: gui/ScrPartitionManual.py:483
msgid "Unable To Edit"
msgstr "Nem módosítható"

#: gui/ScrPartitionManual.py:484
#, python-format
msgid ""
"You cannot edit this device:\n"
"\n"
"%s"
msgstr ""
"Ez az eszköz nem módosítható:\n"
"\n"
"%s"

#: gui/ScrKahyaCheck.py:78
msgid "No storage device found."
msgstr "Nem található tárolóeszköz."

#: gui/ScrRescuePassword.py:99 gui/ScrUsers.py:214
msgid "Don't use your user name or name as a password"
msgstr "Ne használja jelszónak a teljes nevét vagy a felhasználónevét"

#: gui/ScrRescuePassword.py:102 gui/ScrUsers.py:217
msgid "Passwords do not match"
msgstr "A jelszavak nem egyeznek"

#: gui/ScrRescuePassword.py:105 gui/ScrUsers.py:220
msgid "Password is too short"
msgstr "A jelszó túl rövid"

#: gui/ScrRescuePassword.py:120 gui/ScrRescue.py:92
msgid "Cannot Rescue"
msgstr ""

#: gui/ScrRescuePassword.py:121 gui/ScrRescue.py:93
#, fuzzy
msgid "Your current installation cannot be rescued."
msgstr "Automatikus telepítés lett kiválasztva."

#: gui/ScrRescuePassword.py:145
msgid "Super User"
msgstr "Rendszergazda"

#: gui/YaliDialog.py:240
msgid "Don't ask again"
msgstr "Ne kérdezze újra"

#: gui/YaliDialog.py:245
msgid "Do you want to continue?"
msgstr "Akarja folytatni?"

#: gui/YaliDialog.py:260
msgid "Information"
msgstr "Információ"

#: gui/YaliDialog.py:262
msgid "OK"
msgstr "OK"

#: gui/YaliDialog.py:453
msgid "Error reporting"
msgstr "Hibajelentés"

#: gui/ScrCheckCD.py:62 gui/Ui/checkcdwidget.py:213
msgid "Validate"
msgstr "Érvényesítés"

#: gui/ScrCheckCD.py:68
msgid "Starting validation..."
msgstr "Érvényesítés indítása..."

#: gui/ScrCheckCD.py:82
msgid "Package validation is in progress. Please wait until it is completed."
msgstr ""

#: gui/ScrCheckCD.py:89
#, python-format
msgid "Validating %s"
msgstr "Érvényesítés %s"

#: gui/ScrCheckCD.py:97
#, python-format
msgid ""
"Validation of %s package failed.Please remaster your installation medium "
"andreboot."
msgstr ""
"A %s csomag érvényesítése meghiúsult. Ellenőtizze a telepítő médiát és "
"indítsa újra a rendszert."

#: gui/ScrCheckCD.py:101
msgid "Skip Validation"
msgstr "Érvényesítés kihagyása"

#: gui/ScrCheckCD.py:101
msgid "Skip Package"
msgstr "Csomag kihagyása"

#: gui/ScrCheckCD.py:101 gui/Ui/exception.py:73 storage/__init__.py:930
msgid "Reboot"
msgstr "Újraindítás"

#: gui/ScrCheckCD.py:115
msgid ""
"<font color=\"#FFF\"><b>Validation succeeded. You can proceed with the "
"installation.</b></font>"
msgstr ""
"<font color=\"#FFF\"><b>Az ellenőrzés sikeres volt. Továbbléphet a "
"telepítésre.</b></font>"

#: gui/ScrCheckCD.py:127
#, fuzzy
msgid "Package validation is finished."
msgstr "Csomagtelepítési beállítások"

#: gui/shrink_gui.py:23
msgid "Partitions to Shrink"
msgstr "Zsugorítandó partíciók"

#: gui/shrink_gui.py:47
msgid "Resize FileSystem Error"
msgstr "Fájlrendszer átméretezési hiba"

#: gui/shrink_gui.py:48
#, python-format
msgid "%(device)s: %(msg)s"
msgstr "%(device)s: %(msg)s"

#: gui/shrink_gui.py:56
msgid "Resize Device Error"
msgstr "Eszköz átméretezési hiba"

#: gui/shrink_gui.py:57
#, python-format
msgid "%(name)s: %(msg)s"
msgstr "%(name)s: %(msg)s"

#: gui/raid_gui.py:26 gui/raid_gui.py:96 gui/raid_gui.py:124
msgid "Invalid Raid Members"
msgstr "Érvénytelen Raid tagok"

#: gui/raid_gui.py:27
msgid ""
"At least two unused software RAID partitions are needed to create a RAID "
"device.\n"
"\n"
"First create at least two partitions of type \"software RAID\", and then "
"select the \"RAID\" option again."
msgstr ""
"Legalább két nem használt szoftver RAID partíció szükséges egy RAID eszköz "
"létrehozásához.\n"
"\n"
"Először készítsen két \"szoftver RAID\" típusú partíciót, majd válassza a "
"\"RAID\" opciót újra."

#: gui/raid_gui.py:37
msgid "Make RAID Device"
msgstr "RAID eszköz létrehozása"

#: gui/raid_gui.py:40
#, python-format
msgid "Edit RAID Device: %s"
msgstr "RAID eszköz módosítása: %s"

#: gui/raid_gui.py:42
msgid "Edit RAID Device"
msgstr "RAID eszköz módosítása"

#: gui/raid_gui.py:68 gui/partition_gui.py:65 gui/lvm_gui.py:613
msgid "Mount Point Error"
msgstr "Csatolási pont hiba"

#: gui/raid_gui.py:82 gui/partition_gui.py:79 gui/lvm_gui.py:644
msgid "Mount point in use"
msgstr "Csatolási pont használatban van"

#: gui/raid_gui.py:83 gui/partition_gui.py:80 gui/lvm_gui.py:645
#, python-format
msgid "The mount point \"%s\" is in use. Please pick another."
msgstr "A \"%s\" csatolási pont már használatban van. Válasszon másikat."

#: gui/raid_gui.py:97 storage/devices/raidarray.py:60
#, python-format
msgid "A RAID%(level)d set requires at least %(min_member)d member"
msgstr "A RAID%(level)d készlet legalább %(min_member)d tagot igényel."

#: gui/ScrLicense.py:77
msgid "License text could not be found."
msgstr "A licensz szövege nem található."

#: gui/ScrRescue.py:54
#, fuzzy
msgid "Mount failed"
msgstr "Nem sikerült csatlakozni"

#: gui/ScrRescue.py:55
#, python-format
msgid ""
"The following error occurred when mounting the file systems listed in /etc/"
"fstab.  Please fix this problem and try to rescue again.\n"
"%s"
msgstr ""

#: gui/ScrDateTime.py:169
msgid "Adjusting time settings"
msgstr "Idő beállítása"

#: gui/ScrDateTime.py:208 gui/ScrAdmin.py:96
msgid "Storage Devices initialising..."
msgstr "Tárolóeszközök inicializálása..."

#: gui/ScrAdmin.py:154
msgid "Password is too short."
msgstr "A jelszó túl rövid."

#: gui/ScrAdmin.py:162
msgid "Passwords do not match."
msgstr "A jelszavak nem egyeznek."

#: gui/ScrAdmin.py:167
msgid "Do not use your username as your password."
msgstr "Ne használj a felhasználónevét jelszónak."

#: gui/ScrAdmin.py:177
msgid "Hostname cannot be longer than 64 characters."
msgstr "A gépnév nem lehet 64 karakternél hosszabb."

#: gui/ScrAdmin.py:190
msgid "Hostname contains invalid characters."
msgstr "A gépnév érvénytelen karaktereket tartalmaz."

#: gui/storageGuiHelpers.py:71 gui/lvm_gui.py:402 gui/lvm_gui.py:432
#: gui/lvm_gui.py:445 gui/lvm_gui.py:480 gui/lvm_gui.py:696 gui/lvm_gui.py:718
msgid "Not enough space"
msgstr "Nincs elég szabad terület"

#: gui/storageGuiHelpers.py:72
msgid ""
"You cannot remove this physical volume because\n"
"otherwise the volume group will be too small to\n"
"hold the currently defined logical volumes."
msgstr ""
"A fizikai kötet nem távolítható el, mert a VG\n"
"túl kicsi lesz a jelenlegi logikai kötetekhez."

#: gui/ScrGoodbye.py:37
msgid "Running post-install operations..."
msgstr "Telepítési utóműveletek végrehajtása..."

#: gui/ScrGoodbye.py:49
msgid "Press <b>Restart</b> to restart the computer."
msgstr "Nyomja meg az <b>Újraindítás</b> gombot a számítógép újraindításához."

#: gui/ScrGoodbye.py:49 gui/ScrSummary.py:46
msgid "Restart"
msgstr "Újraindítás"

#: gui/ScrGoodbye.py:50
msgid "<b>Please wait while restarting...</b>"
msgstr "Újraindítás. Kérem várjon..."

#: gui/ScrGoodbye.py:64
msgid "Setting timezone..."
msgstr "Időzóna beállítása..."

#: gui/ScrGoodbye.py:65
msgid "Migrating Xorg configuration..."
msgstr "Xorg beállítások importálása..."

#: gui/ScrGoodbye.py:66
msgid "Copying repository index..."
msgstr "Tároló index másolása..."

#: gui/ScrGoodbye.py:69
msgid "Setting hostname..."
msgstr "Gépnév beállítása..."

#: gui/ScrGoodbye.py:70
msgid "Setting root password..."
msgstr "Rendszergazda jelszó beállítása..."

#: gui/ScrGoodbye.py:73
#, fuzzy
msgid "Resetting user password..."
msgstr "Rendszergazda jelszó beállítása..."

#: gui/ScrGoodbye.py:76
msgid "Setup First-Boot..."
msgstr "Első indulás beállítása..."

#: gui/ScrGoodbye.py:79
#, fuzzy
msgid "Teardown First-Boot..."
msgstr "Első indulás beállítása..."

#: gui/ScrGoodbye.py:83
msgid "Adding users..."
msgstr "Felhasználók hozzáadása..."

#: gui/ScrGoodbye.py:88
msgid "Installing bootloader..."
msgstr "Rendszertöltő telepítése..."

#: gui/ScrGoodbye.py:89
#, fuzzy
msgid "Writing bootloader config..."
msgstr "Rendszertöltő kiírása..."

#: gui/ScrGoodbye.py:90 gui/ScrGoodbye.py:94
msgid "Stopping to D-Bus..."
msgstr "D-BUS leállítása..."

#: gui/ScrGoodbye.py:91 gui/ScrGoodbye.py:95
msgid "Teardown storage subsystem..."
msgstr ""

#: gui/ScrRescuePisi.py:37
msgid "Starting D-Bus..."
msgstr "D-Bus indítása..."

#: gui/ScrRescuePisi.py:38
msgid "Connecting to D-Bus..."
msgstr "Csatlakozás a D-BUShoz..."

#: gui/ScrRescuePisi.py:39
msgid "Fetching history..."
msgstr "Előzmények összegyűjtése..."

#: gui/ScrRescuePisi.py:69
msgid "Please Wait..."
msgstr "Kérem várjon..."

#: gui/ScrRescuePisi.py:75
msgid "No connection available"
msgstr "Nincs elérhető kapcsolat"

#: gui/ScrRescuePisi.py:116
#, python-format
msgid "Operation %(no)s : %(date)s - %(type)s"
msgstr "Művelet %(no)s : %(date)s - %(type)s"

#: gui/ScrRescuePisi.py:170
#, python-format
msgid "Connecting to network %s..."
msgstr "Csatlakozás a %s hálózathoz..."

#: gui/ScrRescuePisi.py:176 gui/ScrRescuePisi.py:177
msgid "Connection failed"
msgstr "Nem sikerült csatlakozni"

#: gui/ScrRescuePisi.py:180 gui/ScrRescuePisi.py:181
msgid "Connected"
msgstr "Csatlakozva"

#: gui/ScrDriveSelection.py:96
#, python-format
msgid "Device Path: %s"
msgstr ""

#: gui/ScrDriveSelection.py:112 gui/YaliWindow.py:381
#: storage/storageset.py:383 storage/storageset.py:459
msgid "Error"
msgstr "Hiba"

#: gui/ScrDriveSelection.py:113
msgid "You must select at least one drive to be used for installation."
msgstr "Ki kell választani egy meghajtót a telepítéshez."

#: gui/partition_gui.py:34
#, python-format
msgid "Create Partition on %(path)s (%(model)s)"
msgstr "Partíció létrehozása %(path)s (%(model)s)"

#: gui/partition_gui.py:38
#, python-format
msgid "Edit Partition %s"
msgstr "%s partíció módosítása"

#: gui/partition_gui.py:40
msgid "Edit Partition"
msgstr "Partíció módosítása"

#: gui/partition_gui.py:103
msgid "Error With Request"
msgstr "Hiba történt"

#: gui/ScrUsers.py:127 gui/ScrUsers.py:359
msgid "Update"
msgstr "Frissítés"

#: gui/ScrUsers.py:266
msgid "This user name is already taken, please choose another one."
msgstr "Ez a felhasználónév már foglalt, válasszon másikat."

#: gui/ScrUsers.py:270
msgid "The user name contains invalid characters."
msgstr "A felhasználónév érvénytelen karaktereket tartalmaz."

#: gui/ScrUsers.py:273
msgid "The real name contains invalid characters."
msgstr "A teljes név érvénytelen karaktereket tartalmaz."

#: gui/ScrUsers.py:281
msgid "User ID used before, choose another one!"
msgstr "A felhasználó azonosító már foglalt, válasszon másikat."

#: gui/ScrUsers.py:286 gui/ScrUsers.py:329 gui/ScrUsers.py:413
#: gui/Ui/setupuserswidget.py:510 gui/Ui/volumegroup.py:127
msgid "Add"
msgstr "Hozzáadás"

#: gui/YaliWindow.py:90
msgid "Pixmaps resources file doesn't exists"
msgstr "Kép forrásfájlok nem találhatók"

#: gui/YaliWindow.py:123
msgid "Style file doesn't exists"
msgstr "Stílus fájl nem található"

#: gui/YaliWindow.py:130
msgid "Release file doesn't exists"
msgstr "Kiadási fájl nem található"

#: gui/YaliWindow.py:138
msgid "Turn Off Computer"
msgstr "Számítógép kikapcsolása"

#: gui/YaliWindow.py:139
msgid "Restart Computer"
msgstr "Számítógép újraindítása"

#: gui/YaliWindow.py:140
msgid "Restart YALI"
msgstr "YALI újraindítása"

#: gui/YaliWindow.py:161 gui/YaliWindow.py:178 sysutils.py:53
msgid "right"
msgstr "jobb"

#: gui/YaliWindow.py:177 gui/YaliWindow.py:180 sysutils.py:52
msgid "left"
msgstr "bal"

#: gui/YaliWindow.py:181
msgid "Mouse Settings"
msgstr "Egér beállítások"

#: gui/YaliWindow.py:182
#, python-format
msgid "You just clicked the <b>%s</b> mouse button."
msgstr "A <b>%s</b> egérgombbal kattintott."

#: gui/YaliWindow.py:183
#, python-format
msgid "Do you want to switch to the <b>%s</b> handed configuration?"
msgstr "Át akar váltani <b>%s</b>kezes egérre?"

#: gui/YaliWindow.py:213
msgid "Are you sure you want to shut down your computer now?"
msgstr "Biztosan ki akarja kapcsolni a számítógépet?"

#: gui/YaliWindow.py:218
msgid "Are you sure you want to restart your computer now?"
msgstr "Biztosan újraindítja a számítógépet?"

#: gui/YaliWindow.py:223
msgid "Are you sure you want to restart the YALI installer now?"
msgstr "Biztosan újraindítja a YALI telepítőt?"

#: gui/YaliWindow.py:244
msgid "Terminal"
msgstr "Terminál"

#: gui/YaliWindow.py:249
msgid "Tetris"
msgstr "Tetris"

#: gui/YaliWindow.py:382
#, fuzzy, python-format
msgid "An error occurred when attempting to load screens:%s"
msgstr ""
"Hiba történt az egyik interfész komponens betöltése közben.\n"
"\n"
"className = %s.Widget"

#: gui/YaliWindow.py:417 gui/Ui/main.py:258
msgid "Release Notes"
msgstr "Kiadási megjegyzések"

#: gui/YaliWindow.py:440
msgid "Release notes could not be loaded."
msgstr "A kiadási megjegyzések nem tölthetők be."

#: gui/ScrBootloader.py:99 gui/Ui/bootloaderwidget.py:145
msgid "The first sector of"
msgstr "Első szektor"

#: gui/ScrSummary.py:47
msgid "<b><p>Are you sure you want to restart the computer?</p></b>"
msgstr "<b><p>Biztosan újraindítja a számítógépet?</p></b>"

#: gui/ScrSummary.py:59 gui/ScrSummary.py:211 gui/ScrSummary.py:218
#: gui/Ui/main.py:262
msgid "Next"
msgstr "Következő"

#: gui/ScrSummary.py:68
#, python-format
msgid "Installation starts in <b>%s</b> seconds"
msgstr "A telepítés <b>%s</b> másodpercen belül elindul"

#: gui/ScrSummary.py:76
msgid "Start Installation"
msgstr "Telepítés indítása"

#: gui/ScrSummary.py:78
msgid "Apply Settings"
msgstr "Beállítások alkalmazása"

#: gui/ScrSummary.py:95
msgid "Keyboard Settings"
msgstr "Billentyűzet beállítások"

#: gui/ScrSummary.py:97
#, python-format
msgid "Selected keyboard layout is <b>%s</b>"
msgstr "A kiválasztott billentyűzetkiosztás <b>%s</b>"

#: gui/ScrSummary.py:103
msgid "Date/Time Settings"
msgstr "Dátum/idő beállítása"

#: gui/ScrSummary.py:105
#, python-format
msgid "Selected TimeZone is <b>%s</b>"
msgstr "A kiválasztott időzóna <b>%s</b>"

#: gui/ScrSummary.py:111
msgid "User Settings"
msgstr "Felhasználói beállítások"

#: gui/ScrSummary.py:113
#, python-format
msgid "User %(username)s (<b>%(realname)s</b>) added."
msgstr "%(username)s (<b>%(realname)s</b>) felhasználó hozzáadva."

#: gui/ScrSummary.py:115
#, python-format
msgid ""
"User %(username)s (<b>%(realname)s</b>) added with <u>administrator "
"privileges</u>."
msgstr ""
"%(username)s (<b>%(realname)s</b>) felhasználó <u>adminisztrátori jogokkal</"
"u> hozzáadva."

#: gui/ScrSummary.py:121
msgid "Hostname Settings"
msgstr "Gépnév beállítása"

#: gui/ScrSummary.py:123
#, python-format
msgid "Hostname is set as <b>%s</b>"
msgstr "<b>%s</b> gépnév beállítva"

#: gui/ScrSummary.py:129
msgid "Partition Settings"
msgstr "Partíció beállítások"

#: gui/ScrSummary.py:136
msgid "Automatic Partitioning selected."
msgstr "Automatikus partícionálás kiválasztva."

#: gui/ScrSummary.py:138
msgid "Use All Space"
msgstr "Teljes terület használata"

#: gui/ScrSummary.py:139
#, python-format
msgid ""
"Removes all partitions on the selected %s device(s). <b><u>This includes "
"partitions created by other operating systems.</u></b>"
msgstr ""
"A %s eszköz(ök)ön minden partíció törlésre kerül. <b><u>Ebbe beletartoznak a "
"más operációs rendszerek által készített partíciók is</u></b>"

#: gui/ScrSummary.py:143
msgid "Replace Existing Linux System(s)"
msgstr "Létező linux rendszerek lecserélése"

#: gui/ScrSummary.py:144
#, python-format
msgid ""
"Removes all Linux partitions on the selected%s device(s). This does not "
"remove other partitions you may have on your storage device(s) (such as VFAT "
"or FAT32)"
msgstr ""
"A kiválasztott %s eszköz(ök) minden linux partíciója eltávolításra kerül. Az "
"eszközön lévő más partíciók (pl. VFAT, FAT32) nem lesznek eltávolítva."

#: gui/ScrSummary.py:149 gui/Ui/autopartwidget.py:173
msgid "Use Free Space"
msgstr "Szabad terület használata"

#: gui/ScrSummary.py:150
#, python-format
msgid ""
"Retains your current data and partitions and uses only the unpartitioned "
"space on the selected %s device(s), assuming you have enough free space "
"available."
msgstr ""
"A létező partíciók és adatok megtartása, és csak a kiválasztott %s "
"eszköz(ök) nem partícionált részének felhasználása, feltételezve, hogy "
"elegendő szabad hely áll rendelkezésre."

#: gui/ScrSummary.py:156
msgid "Manual Partitioning selected."
msgstr "Kézi partícionálás lett kiválasztva."

#: gui/ScrSummary.py:164
msgid "Bootloader Settings"
msgstr "Rendszertöltő beállítások"

#: gui/ScrSummary.py:165
#, python-format
msgid "GRUB will be installed to <b>%s</b>."
msgstr "A GRUB a <b>%s</b>-re kerül."

#: gui/ScrSummary.py:167
msgid "GRUB will not be installed."
msgstr "A GRUB nem kerül telepítésre."

#: gui/ScrSummary.py:174
msgid "Package Installation Settings"
msgstr "Csomagtelepítési beállítások"

#: gui/ScrSummary.py:175
#, fuzzy, python-format
msgid "Collection <b>%s</b> selected"
msgstr "Kézi telepítés (%s) lett kiválasztva."

#: gui/ScrSummary.py:195
msgid "Confirm"
msgstr "Jóváhagyás"

#: gui/ScrSummary.py:196
#, fuzzy
msgid ""
"The partitioning options you have selected will now be written to disk. Any "
"data on deleted or reformatted partitions will be lost."
msgstr ""
"A kiválasztott partícionálási beállítások kiírásra kerülnek\n"
"a lemezre. A törlendő vagy újraformázandó partíciók minden\n"
"adata törlődik."

#: gui/ScrSummary.py:201
msgid "Write Changes to Disk"
msgstr "Változtatások kiírása a lemezre"

#: gui/ScrSummary.py:201
msgid "Go Back"
msgstr "Vissza"

#: gui/ScrSummary.py:287
msgid "Proprietary Hardware Drivers"
msgstr "Zárt meghajtó programok"

#: gui/ScrSummary.py:288
#, fuzzy
msgid ""
"<qt>Proprietary drivers are available which may be required to utilize the "
"full capabilities of your video card. These drivers are developed by the "
"hardware manufacturer and not supported by Pisi Linux developers since their "
"source code is not publicly available.<br><br><b>Do you want to install and "
"use these proprietary drivers instead of the default drivers?</b></qt>"
msgstr ""
"<qt>Zárt meghajtó programok elérhetők a videokártyájához, amelyekkel a "
"maximális teljesítmény érhető el. Ezeket a meghajtókat a hardver gyártója "
"készíti, forráskódjuk nem publikus ezért a Pardus fejlesztői nem tudnak "
"hozzá támogatást nyújtani.<br><br><b>Szeretné ezeket a meghajtókat "
"telepíteni és használni az alapértelmezettek helyett?</b></qt>"

#: gui/Ui/manualpartwidget.py:193
msgid "Device"
msgstr ""

#: gui/Ui/manualpartwidget.py:194
#, fuzzy
msgid "Mount Point"
msgstr "Csatolási pont hiba"

#: gui/Ui/manualpartwidget.py:195
msgid "Label"
msgstr ""

#: gui/Ui/manualpartwidget.py:196
msgid "Type"
msgstr ""

#: gui/Ui/manualpartwidget.py:198 gui/Ui/volumegroup.py:126
msgid "Size"
msgstr ""

#: gui/Ui/manualpartwidget.py:199
msgid "Create"
msgstr ""

#: gui/Ui/manualpartwidget.py:200 gui/Ui/setupuserswidget.py:511
#: gui/Ui/volumegroup.py:128
msgid "Edit"
msgstr ""

#: gui/Ui/manualpartwidget.py:201 gui/Ui/setupuserswidget.py:512
#: gui/Ui/volumegroup.py:129 gui/lvm_gui.py:552
#: storage/storageBackendHelpers.py:92 storage/storageBackendHelpers.py:296
msgid "Delete"
msgstr "Törlés"

#: gui/Ui/manualpartwidget.py:202
msgid "Reset"
msgstr ""

#: gui/Ui/raid.py:114
msgid "Raid Device:"
msgstr ""

#: gui/Ui/raid.py:115 gui/Ui/partition.py:152
msgid "Use:"
msgstr ""

#: gui/Ui/raid.py:116
#, fuzzy
msgid "Filesystem:"
msgstr "Fájlrendszer"

#: gui/Ui/raid.py:118 gui/Ui/partition.py:158 gui/Ui/logicalvolume.py:160
msgid "Migrate"
msgstr ""

#: gui/Ui/raid.py:119
msgid "Raid Level:"
msgstr ""

#: gui/Ui/raid.py:120
#, fuzzy
msgid "Raid Members:"
msgstr "Érvénytelen Raid tagok"

#: gui/Ui/raid.py:121
msgid "Number of spares:"
msgstr ""

#: gui/Ui/collectionitem.py:93
#, fuzzy
msgid "Form"
msgstr "Formázás"

#: gui/Ui/partition.py:153 gui/Ui/partedit.py:174 gui/Ui/partitionedit.py:154
#: gui/Ui/logicalvolume.py:154
msgid "Size :"
msgstr ""

#: gui/Ui/partition.py:154 gui/Ui/partition.py:156 gui/Ui/partedit.py:175
#: gui/Ui/partitionshrinkwidget.py:102 gui/Ui/partresize.py:102
#: gui/Ui/partitionedit.py:155 gui/Ui/logicalvolume.py:155
#: gui/Ui/logicalvolume.py:157
msgid " MB"
msgstr ""

#: gui/Ui/partition.py:155 gui/Ui/partresize.py:104
#: gui/Ui/logicalvolume.py:156
msgid "Resize"
msgstr ""

#: gui/Ui/partition.py:159 gui/Ui/partedit.py:178 gui/Ui/partitionedit.py:156
#: gui/Ui/logicalvolume.py:158
#, fuzzy
msgid "File System :"
msgstr "Fájlrendszer"

#: gui/Ui/partition.py:160
#, fuzzy
msgid "Force to be a primary partition"
msgstr "Raid partíció létrehozása"

#: gui/Ui/license.py:117
msgid ""
"<html><head/><body><p>Before installing Pisi Linux on your computer, please "
"read and accept the terms of free / open source licenses of the softwares "
"included in this installation medium. <a href=\"#\"><span style=\" text-"
"decoration: underline; color:#56a2c0;\">License texts</span></a></p></body></"
"html>"
msgstr ""

#: gui/Ui/license.py:118
msgid "I understand and accept the terms"
msgstr ""

#: gui/Ui/installprogress.py:76
msgid "Installing Package: "
msgstr ""

#: gui/Ui/rootpasswidget.py:142
msgid "Administrator password"
msgstr ""

#: gui/Ui/rootpasswidget.py:143
#, fuzzy
msgid "Confirm password"
msgstr "Visszaállítás jóváhagyása"

#: gui/Ui/rootpasswidget.py:144
msgid "Computer Name"
msgstr ""

#: gui/Ui/main.py:257
msgid "Yali"
msgstr ""

#: gui/Ui/main.py:259
msgid "Previous Screen"
msgstr ""

#: gui/Ui/main.py:260
#, fuzzy
msgid "Back"
msgstr "Vissza"

#: gui/Ui/main.py:261
msgid "Next Screen"
msgstr ""

#: gui/Ui/partedit.py:173 gui/Ui/partitionedit.py:153
#: gui/Ui/logicalvolume.py:153
msgid "Use :"
msgstr ""

#: gui/Ui/partedit.py:176
#, fuzzy
msgid "Format :"
msgstr "Formázás"

#: gui/Ui/partedit.py:177
#, fuzzy
msgid "Yes, format this partition"
msgstr "LVM partíció létrehozása"

#: gui/Ui/partedit.py:179
#, fuzzy
msgid "Delete Partition"
msgstr "Partíció módosítása"

#: gui/Ui/partedit.py:180
#, fuzzy
msgid "Resize Partition"
msgstr "Partíció módosítása"

#: gui/Ui/partedit.py:181
msgid "Changes will be applied after Summary Screen."
msgstr ""

#: gui/Ui/partedit.py:182
msgid "Refresh Disks"
msgstr ""

#: gui/Ui/partedit.py:183
#, fuzzy
msgid "Reset All Changes"
msgstr "Teljes terület használata"

#: gui/Ui/partedit.py:184
msgid "Apply"
msgstr ""

#: gui/Ui/connectionlist.py:84
msgid ""
"To use PiSi History support, you may need to be online. You can use a "
"connection profile from the list below:"
msgstr ""

#: gui/Ui/connectionlist.py:85 gui/Ui/autopartquestion.py:92
#: gui/Ui/dialog.py:78
msgid "X"
msgstr ""

#: gui/Ui/connectionlist.py:86
#, fuzzy
msgid "Connect"
msgstr "Csatlakozva"

#: gui/Ui/autopartwidget.py:169
#, fuzzy
msgid "Use All Disk"
msgstr "Teljes terület használata"

#: gui/Ui/autopartwidget.py:171
msgid "Shrink Current System"
msgstr ""

#: gui/Ui/autopartwidget.py:175
#, fuzzy
msgid "Manual Partitioning"
msgstr "Kézi partícionálás lett kiválasztva."

#: gui/Ui/partitionshrinkwidget.py:100 gui/Ui/partitionshrink.py:73
msgid ""
"Which partition would you like to shrink to make room for your installation?"
msgstr ""

#: gui/Ui/partitionshrinkwidget.py:101
msgid "Shrink partition to size (in MB) :"
msgstr ""

#: gui/Ui/partitionshrinkwidget.py:104
msgid "Shrink"
msgstr ""

#: gui/Ui/rescuepisiwidget.py:84
msgid "<b>Connection status:</b>"
msgstr ""

#: gui/Ui/rescuepisiwidget.py:85
msgid ""
"To use PiSi's history feature, you may need to be online. Select connection "
"profile."
msgstr ""

#: gui/Ui/rescuepisiwidget.py:86
msgid "Select Connection"
msgstr ""

#: gui/Ui/rescuepisiwidget.py:87
msgid "Select the operation to undo:"
msgstr ""

#: gui/Ui/autopartquestion.py:91
msgid ""
"There appears to be more than one resizeable partition. You can select a "
"partition from the list below or YALI will select one for you."
msgstr ""

#: gui/Ui/autopartquestion.py:93
msgid "Automatically choose the partition to resize (recommended)"
msgstr ""

#: gui/Ui/autopartquestion.py:94
msgid "I will choose the target"
msgstr ""

#: gui/Ui/autopartquestion.py:95
#, fuzzy
msgid "Use Selected"
msgstr "Szabad terület használata"

#: gui/Ui/checkcdwidget.py:210
msgid ""
"You can validate the integrity of the installation packages. Although this "
"is an optional step, we highly recommend to do the validation in order to "
"avoid any possible errors during the installation process."
msgstr ""

#: gui/Ui/checkcdwidget.py:211
#, fuzzy
msgid "Validation failed"
msgstr "Érvényesítés %s"

#: gui/Ui/checkcdwidget.py:212
#, fuzzy
msgid "Validation succeeded"
msgstr "Érvényesítés %s"

#: gui/Ui/partresize.py:99
msgid ""
"Changes will be applied when you click \"Resize\". To cancel the changes, "
"click <b>\"Cancel\".\n"
"<br><br>\n"
"Warning: A resizing operation may corrupt the partition, rendering the data "
"on it unreachable. Make sure that you have backed up the data. Note that "
"this operation cannot be undone.<b>"
msgstr ""

#: gui/Ui/partitionedit.py:157
#, fuzzy
msgid "Force to be primary partition"
msgstr "LVM partíció létrehozása"

#: gui/Ui/rescuewidget.py:125
msgid "Choose what do you want to do to repair your system"
msgstr ""

#: gui/Ui/rescuewidget.py:126
#, fuzzy
msgid "Reinstall bootloader"
msgstr "Rendszertöltő telepítése..."

#: gui/Ui/rescuewidget.py:127
#, fuzzy
msgid "Reset forgotten password"
msgstr "Rendszergazda jelszó beállítása..."

#: gui/Ui/rescuewidget.py:128
msgid "Return back to a previous system state"
msgstr ""

#: gui/Ui/keyboardwidget.py:142
#, fuzzy
msgid "Keyboard Layouts"
msgstr "Billentyűzet beállítások"

#: gui/Ui/keyboardwidget.py:143
msgid "Test Layout"
msgstr ""

#: gui/Ui/rescuepasswordwidget.py:136
msgid "Choose the user you want to reset the password:"
msgstr ""

#: gui/Ui/rescuepasswordwidget.py:137
msgid "Password:"
msgstr ""

#: gui/Ui/rescuepasswordwidget.py:138 gui/Ui/setupuserswidget.py:504
#, fuzzy
msgid "Confirm Password"
msgstr "Visszaállítás jóváhagyása"

#: gui/Ui/rescuepasswordwidget.py:139
#, fuzzy
msgid "Reset Password"
msgstr "Rendszergazda jelszó beállítása..."

#: gui/Ui/setupuserswidget.py:501
msgid "User Name"
msgstr ""

#: gui/Ui/setupuserswidget.py:502
msgid "Real Name"
msgstr ""

#: gui/Ui/setupuserswidget.py:503
msgid "Password"
msgstr ""

#: gui/Ui/setupuserswidget.py:505
msgid "Custom User ID"
msgstr ""

#: gui/Ui/setupuserswidget.py:506
msgid "Not recommended"
msgstr ""

#: gui/Ui/setupuserswidget.py:507
msgid "Bypass authorization attempts for this user"
msgstr ""

#: gui/Ui/setupuserswidget.py:508
msgid "Add user to administrator (wheel) group"
msgstr ""

#: gui/Ui/setupuserswidget.py:509
msgid "Select auto login user"
msgstr ""

#: gui/Ui/setupuserswidget.py:514
msgid "Advanced"
msgstr ""

#: gui/Ui/partitionshrink.py:74
msgid "Shrink partition to size (in MB)"
msgstr ""

#: gui/Ui/help.py:65
msgid "help content"
msgstr ""

#: gui/Ui/rescuegrubwidget.py:118
msgid "Select where to install the GRUB bootloader"
msgstr ""

#: gui/Ui/rescuegrubwidget.py:119
msgid "First bootable disk (recommended)"
msgstr ""

#: gui/Ui/rescuegrubwidget.py:120
msgid "Disk partition where Pisi Linux is installed"
msgstr ""

#: gui/Ui/rescuegrubwidget.py:121
msgid "Selected disk below"
msgstr ""

#: gui/Ui/datetimewidget.py:181
msgid "Date"
msgstr ""

#: gui/Ui/datetimewidget.py:182
msgid "Time"
msgstr ""

#: gui/Ui/datetimewidget.py:183
msgid "Timezone"
msgstr ""

#: gui/Ui/logicalvolume.py:152
#, fuzzy
msgid "Logical Volume:"
msgstr "Logikai kötet (LV)"

#: gui/Ui/welcome.py:98
msgid ""
"Pisi Linux is installed and running successfully... \n"
"\n"
"Before you login to system, you need to create your first user and set the "
"system wide configurations. "
msgstr ""

#: gui/Ui/createdevicewidget.py:143
#, fuzzy
msgid "Standard Partition"
msgstr "Partíció módosítása"

#: gui/Ui/createdevicewidget.py:151
#, fuzzy
msgid "Raid Member"
msgstr "Érvénytelen Raid tagok"

#: gui/Ui/createdevicewidget.py:153
#, fuzzy
msgid "Raid Array"
msgstr "RAID tömb"

#: gui/Ui/exception.py:71
msgid "Unhandled exception occured"
msgstr ""

#: gui/Ui/exception.py:72
msgid ""
"Please fill a bug report at http://bugs.pisilinux.org.tr/ attaching the "
"following backtrace."
msgstr ""

#: gui/Ui/exception.py:74
msgid "Show Backtrace"
msgstr ""

#: gui/Ui/volumegroup.py:119
#, fuzzy
msgid "Volume Group Name:"
msgstr "VG"

#: gui/Ui/volumegroup.py:120
#, fuzzy
msgid "Physical Extends"
msgstr "Fizikai kötet"

#: gui/Ui/volumegroup.py:121
#, fuzzy
msgid "Physical Volumes to use:"
msgstr "Fizikai kötet"

#: gui/Ui/volumegroup.py:122
msgid "Total Space:"
msgstr ""

#: gui/Ui/volumegroup.py:123
#, fuzzy
msgid "Free Space:"
msgstr "Szabad terület használata"

#: gui/Ui/volumegroup.py:124
#, fuzzy
msgid "Logical Volumes"
msgstr "Logikai kötet (LV)"

#: gui/Ui/volumegroup.py:125
#, fuzzy
msgid "Mountpoint"
msgstr "Csatolási pont használatban van"

#: gui/Ui/volumegroup.py:130
#, fuzzy
msgid "Used Space:"
msgstr "Teljes terület használata"

#: gui/Ui/bootloaderwidget.py:141
#, fuzzy
msgid "Advanced settings"
msgstr "Idő beállítása"

#: gui/Ui/bootloaderwidget.py:142
#, fuzzy
msgid "Default settings"
msgstr "Dátum/idő beállítása"

#: gui/Ui/bootloaderwidget.py:143
#, fuzzy
msgid "Don't install bootloader"
msgstr "Rendszertöltő telepítése..."

#: gui/Ui/bootloaderwidget.py:144
msgid "The partition where Pisi Linux is installed"
msgstr ""

#: gui/lvm_gui.py:48
msgid "Not enough physical volumes"
msgstr "Nincs elég fizikai kötet."

#: gui/lvm_gui.py:49
msgid ""
"At least one unused physical volume partition is needed to\n"
"create an LVM Volume Group.\n"
"Create a partition or RAID array of type \"physical volume\n"
"(LVM)\" and then select the \"LVM\" option again."
msgstr ""
"Legalább egy használaton kívüli fizikai kötet partíció szükséges\n"
"a logikai kötet létrehozásához.\n"
"Készítsen egy partíciót vagy RAID tömböt \"fizikai kötet (LVM)\"\n"
"típusként, ezután válassza újra az \"LVM\" opciót."

#: gui/lvm_gui.py:60
msgid "Make LVM Volume Group"
msgstr "LVM VG létrehozása"

#: gui/lvm_gui.py:63
#, python-format
msgid "Edit LVM Volume Group: %s"
msgstr "%s LVM VG módosítása"

#: gui/lvm_gui.py:65
msgid "Edit LVM Volume Group"
msgstr "LVM VG módosítása"

#: gui/lvm_gui.py:91
msgid "Invalid Volume Group Name"
msgstr "Érvénytelen VG név"

#: gui/lvm_gui.py:98
msgid "Name in use"
msgstr "A név használatban van"

#: gui/lvm_gui.py:99
#, python-format
msgid "The volume group name \"%s\" is already in use. Please pick another."
msgstr "A \"%s\" VG név már használatban van. Válasszon másikat."

#: gui/lvm_gui.py:403
msgid ""
"The physical extent size cannot be changed because\n"
"otherwise the space required by the currently defined\n"
"logical volumes will be increased to more than the\n"
"available space."
msgstr ""
"A fizikai extent méret nem módosítható, mert\n"
"ez esetben a már definiált kötetek mérete meghaladná\n"
"a rendelkezésre álló területet."

#: gui/lvm_gui.py:411
msgid "Confirm Physical Extent Change"
msgstr "Fizikai extent méret megváltoztatásának jóváhagyása"

#: gui/lvm_gui.py:412
msgid ""
"This change in the value of the physical extent will\n"
"require the sizes of the current logical volume requests\n"
"to be rounded up in size to an integer multiple of\n"
"the physical extent.\n"
"\n"
"This change will take effect\n"
"immediately."
msgstr ""
"Ez változtatás a fizikai extent méretében azt\n"
"eredményezi, hogy az aktuális logikai kötet mérete\n"
"a fizikai extentek egész számú többszörösére változzon.\n"
"\n"
"A változtatás azonnal életbe lép."

#: gui/lvm_gui.py:433
#, python-format
msgid ""
"The physical extent size cannot be changed because\n"
"the value selected (%(curpe)10.2f MB) is larger than the\n"
"smallest physical volume (%(maxpvsize)10.2f MB) in the volume group."
msgstr ""
"A fizikai extent mérete nem változtatható meg, mert\n"
"a kiválasztott érték (%(curpe)10.2f MB) nagyobb, mint a\n"
"legkisebb fizikai kötet (%(maxpvsize)10.2f MB) a VG-ben."

#: gui/lvm_gui.py:446
#, python-format
msgid ""
"The physical extent size cannot be changed because the value selected "
"(%(curpe)10.2f MB) is too large compared to the size of the smallest "
"physical volume (%(maxpvsize)10.2f MB) in the volume group."
msgstr ""
"A fizikai extent mérete nem változtatható meg, mert\n"
"a kiválasztott érték (%(curpe)10.2f MB) túl nagy\n"
"legkisebb fizikai kötet (%(maxpvsize)10.2f MB) méretéhez\n"
"viszonyítva a VG-n belül."

#: gui/lvm_gui.py:458
msgid "Too small"
msgstr "Túl kicsi"

#: gui/lvm_gui.py:459
msgid ""
"This change in the value of the physical extent will waste substantial space "
"on one or more of the physical volumes in the volume group."
msgstr ""
"Ez a fizikai extent méret egy vagy több köteten túl sok kihasználatlan "
"helyfoglaláshoz vezet."

#: gui/lvm_gui.py:481
#, python-format
msgid ""
"The physical extent size cannot be changed because the resulting maximum "
"logical volume size (%10.2f MB) is smaller than one or more of their "
"currently defined logical volumes."
msgstr ""
"A fizikai extent méret nem módosítható, mert az eredményként adódó maximális "
"logikai kötet mérete (%10.2f MB) kisebb mint egy vagy több már definiált "
"logikai kötet."

#: gui/lvm_gui.py:502
msgid "No free slots"
msgstr "Nincs szabad csatolóhely"

#: gui/lvm_gui.py:503
#, python-format
msgid ""
"You cannot create more than %d logical volume \n"
"per volume group."
msgstr ""
"Maximum %d logikai kötet hozható létre \n"
"egy VG-ben."

#: gui/lvm_gui.py:510
msgid "No free space"
msgstr "Nincs szabad hely"

#: gui/lvm_gui.py:511
msgid ""
"There is no room left in the volume group to create new\n"
"logical volumes. To add a logical volume you must reduce\n"
"the size of one or more of the currently existing logical\n"
"volumes"
msgstr ""
"Nincs több hely a VG-ben új logikai kötet\n"
"létrehozására. Új kötet hozzáadásához csökkentse\n"
"egy vagy több létező logikai kötet méretét."

#: gui/lvm_gui.py:548 storage/storageBackendHelpers.py:88
#: storage/storageBackendHelpers.py:295
msgid "Confirm Delete"
msgstr "Törlés jóváhagyása"

#: gui/lvm_gui.py:549
#, python-format
msgid ""
"Are you sure you want to delete the \n"
"logical volume \"%s\"?"
msgstr "Biztosan törli a \"%s\" logikai kötetet?"

#: gui/lvm_gui.py:582
msgid "Make Logical Volume"
msgstr "Logikai kötet létrehozása"

#: gui/lvm_gui.py:584
#, python-format
msgid "Edit Logical Volume: %s"
msgstr "%s logikai kötet módosítása"

#: gui/lvm_gui.py:656
msgid "Illegal Logical Volume Name"
msgstr "Érvénytelen logikai kötet név"

#: gui/lvm_gui.py:668
msgid "Illegal logical volume name"
msgstr "Érvénytelen logikai kötet név"

#: gui/lvm_gui.py:669
#, python-format
msgid "The logical volume name \"%s\" is already in use. Please pick another."
msgstr "A \"%s\" logikai kötet név már használatban van. Válasszon másikat."

#: gui/lvm_gui.py:683
msgid "Illegal size"
msgstr "Érvénytelen méret"

#: gui/lvm_gui.py:684
msgid "The requested size as entered is not a valid number greater than 0."
msgstr "A megadott méret nem egy nullánál nagyobb érvényes szám."

#: gui/lvm_gui.py:697
#, python-format
msgid ""
"The current requested size (%(size)10.2f MB) is larger than the maximum "
"logical volume size (%(maxlv)10.2f MB). To increase this limit you can "
"create more Physical Volumes from unpartitioned disk space and add them to "
"this Volume Group."
msgstr ""
"A megadott méret (%(size)10.2f MB) nagyobb mint a maximális logikai kötet "
"méret (%(maxlv)10.2f MB). A korlát megemeléséhez készítsen további fizikai "
"köteteket nem partícionált lemezrészekből, és adja hozzá a VG-hez."

#: gui/lvm_gui.py:719
#, python-format
msgid ""
"The size entered for this logical volume (%(size)d MB) combined with the "
"size of the other logical volume(s) exceeds the size of the volume group "
"(%(tmpvgsize)d MB). Please make the volume group larger or make the logical "
"volume smaller."
msgstr ""
"A megadott logikai kötet méret (%(size)d MB) a többi logikai kötet méretével "
"együtt meghaladja a VG méretét (%(tmpvgsize)d MB). Növelje a VG méretét, "
"vagy adjon meg kisebb logikai kötet méretet."

#: postinstall.py:124
#, python-format
msgid "Preparing home directory for %s..."
msgstr "%s saját könyvtárának előkészítése..."

#: util.py:527 util.py:570
msgid "Release file is missing"
msgstr "Kiadási fájl nem található"

#: util.py:529 util.py:572
msgid "Release file is inconsistent"
msgstr "A kiadási fájl érvénytelen"

#: util.py:532 util.py:575
msgid "Invalid xml file"
msgstr "Érvénytelen xml fájl"

#: localedata.py:20
msgid "Turkish"
msgstr "Turkish"

#: localedata.py:22
msgid "Turkish F"
msgstr "Turkish F"

#: localedata.py:22
msgid "Turkish Q"
msgstr "Turkish Q"

#: localedata.py:31
msgid "English"
msgstr "English"

#: localedata.py:42
msgid "English GB"
msgstr "English GB"

#: localedata.py:52
msgid "Greek"
msgstr "Greek"

#: localedata.py:62
msgid "Afrikaans"
msgstr "Afrikaans"

#: localedata.py:72
msgid "Vietnamese"
msgstr "Vietnamese"

#: localedata.py:82
msgid "Catalan"
msgstr "Catalan"

#: localedata.py:93
msgid "Italian"
msgstr "Italian"

#: localedata.py:104
msgid "Czech"
msgstr "Czech"

#: localedata.py:114
msgid "Welsh"
msgstr "Welsh"

#: localedata.py:124
msgid "Arabic"
msgstr "Arabic"

#: localedata.py:134
msgid "Estonian"
msgstr "Estonian"

#: localedata.py:144
msgid "Spanish"
msgstr "Spanish"

#: localedata.py:155
msgid "Russian"
msgstr "Russian"

#: localedata.py:166
msgid "Dutch"
msgstr "Dutch"

#: localedata.py:177
msgid "Portuguese"
msgstr "Portuguese"

#: localedata.py:188
msgid "Norwegian"
msgstr "Norwegian"

#: localedata.py:198
msgid "Icelandic"
msgstr "Icelandic"

#: localedata.py:208
msgid "Polish"
msgstr "Polish"

#: localedata.py:219
msgid "Belgium"
msgstr "Belgium"

#: localedata.py:229
msgid "French"
msgstr "French"

#: localedata.py:240
msgid "Bulgarian"
msgstr "Bulgarian"

#: localedata.py:250
msgid "Slovenian"
msgstr "Slovenian"

#: localedata.py:260
msgid "Croatian"
msgstr "Croatian"

#: localedata.py:270
msgid "German"
msgstr "German"

#: localedata.py:281
msgid "Danish"
msgstr "Danish"

#: localedata.py:291
msgid "Brazilian"
msgstr "Brazilian"

#: localedata.py:301
msgid "Finnish"
msgstr "Finnish"

#: localedata.py:311
msgid "Hungarian"
msgstr "Magyar"

#: localedata.py:322
msgid "Japanese"
msgstr "Japanese"

#: localedata.py:332
msgid "Malayalam"
msgstr "Malayalam"

#: localedata.py:342
msgid "Swedish"
msgstr "Swedish"

#: localedata.py:353
msgid "Macedonian"
msgstr "Macedonian"

#: localedata.py:363
msgid "Slovak"
msgstr "Slovak"

#: localedata.py:373
msgid "Ukrainian"
msgstr "Ukrainian"

#: localedata.py:383
msgid "Serbian"
msgstr "Serbian"

#: storage/storageset.py:298 storage/storageset.py:311
msgid "Invalid mount point"
msgstr "Érvénytelen csatolási pont"

#: storage/storageset.py:299
#, python-format
msgid ""
"An error occurred when trying to create %s.  Some element of this path is "
"not a directory. This is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"%s létrehozása közben hiba lépett fel. Az útvonal valamely eleme nem "
"könyvtár. Ez súlyos hiba, a telepítés nem folytatható.\n"
"\n"
"Nyomja meg az <Enter> gombot a kilépéshez."

#: storage/storageset.py:312
#, python-format
msgid ""
"An error occurred when trying to create %(mountpoint)s: %(msg)s.  This is a "
"fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"Hiba lépett fel a %(mountpoint)s létrehozása közben: %(msg)s.Ez súlyos hiba, "
"a telepítés nem folytatható.\n"
"\n"
"Nyomja meg az <Enter> gombot a kilépéshez."

#: storage/storageset.py:329 storage/storageset.py:350
msgid "Unable to mount filesystem"
msgstr "A fájlrendszer nem csatolható"

#: storage/storageset.py:330
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s.  You may "
"continue installation, but there may be problems."
msgstr ""
"Hiba lépett fel %(path)s eszköz %(mountpoint)s pontba csatolása közben. "
"Folytathatja a telepítést, de problémák adódhatnak."

#: storage/storageset.py:336 storage/__init__.py:75
msgid "Exit installer"
msgstr "Kilépés a telepítőből"

#: storage/storageset.py:351
#, python-format
msgid ""
"An error occurred mounting device %(path)s as %(mountpoint)s: %(msg)s. This "
"is a fatal error and the install cannot continue.\n"
"\n"
"Press <Enter> to exit the installer."
msgstr ""
"Hiba lépett fel a %(path)s eszköz %(mountpoint)s pontba csatolása közben: "
"%(msg)s.Ez súlyos hiba, a telepítés nem folytatható.\n"
"\n"
"Nyomja meg az <Enter> gombot a kilépéshez."

#: storage/storageset.py:386
msgid "Skip"
msgstr "Kihagyás"

#: storage/storageset.py:418
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"is an old-style Linux swap partition.  If you want to use this device for "
"swap space, you must reformat as a new-style Linux swap partition."
msgstr ""
"A lapozóterület:\n"
"\n"
"      %s\n"
"\n"
"régi típusú linux lapozóterület. Ha ezt akarja használni, újra kell "
"formáznia új típusú linux lapozóterületként."

#: storage/storageset.py:429
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"in your /etc/fstab file is currently in use as a software suspend device, "
"which means your system is hibernating. If you are performing a new install, "
"make sure the installer is set to format all swap devices."
msgstr ""
"A lapozóterület:\n"
"\n"
"      %s\n"
"\n"
"Jelenleg hibernálási területként van beállítva. Ha új telepítést végez, "
"győződjön meg róla, hogy minden lapozóterületet formázásra állított be."

#: storage/storageset.py:442
#, python-format
msgid ""
"The swap device:\n"
"\n"
"     %s\n"
"\n"
"does not contain a supported swap volume.  In order to continue "
"installation, you will need to format the device or skip it."
msgstr ""
"A lapozóterület:\n"
"\n"
"      %s\n"
"\n"
"Nem tartalmaz támogatott lapozó kötetet. A telepítés folytatásához vagy "
"formáznia kell, vagy ki kell hagynia."

#: storage/storageset.py:453
#, fuzzy, python-format
msgid ""
"Error enabling swap device %(name)s: %(msg)s<br><br>This most likely means "
"this swap device has not been initialized.<br><br>Press OK to exit the "
"installer."
msgstr ""
"Lapozó eszköz %(name)s aktiválása közben hiba lépett fel: %(msg)s\n"
"\n"
"A lapozó eszköz nem lett inicializálva.\n"
"\n"
"Nyomja meg az OK gombot a kilépéshez."

#: storage/storageset.py:501
msgid "You have not created a bootable partition."
msgstr "Nem hozott létre rendszerindító partíciót."

#: storage/storageset.py:505
msgid "Bootable partitions cannot be on a logical volume."
msgstr "A rendszerindító partíció nem lehet logikai eszközön."

#: storage/storageset.py:509
#, fuzzy
msgid "Bootable partitions cannot be on a raid array."
msgstr "A rendszerindító partíció nem lehet logikai eszközön."

#: storage/storageset.py:516
#, python-format
msgid "Bootable partitions cannot be on an %s filesystem."
msgstr "Rendszerindító partíció nem lehet %s fájlrendszeren."

#: storage/storageset.py:620
msgid "Ignoring noauto entry"
msgstr ""

#: storage/storageset.py:678
#, python-format
msgid "Failed to resolve %s (%s) from fstab"
msgstr ""

#: storage/storageset.py:684
#, python-format
msgid "Unrecognized filesystem type for %s (%s)"
msgstr ""

#: storage/storageset.py:691
#, python-format
msgid "Scanned format (%s) differs from fstab format (%s)"
msgstr ""

#: storage/storageset.py:713
#, python-format
msgid "Cannot open %s for read"
msgstr ""

#: storage/storageset.py:743
#, python-format
msgid "Fstab entry %s is malformed: %s"
msgstr ""

#: storage/bootloader.py:210 storage/bootloader.py:211
#: storage/bootloader.py:213 storage/bootloader.py:214
#, python-format
msgid "%s"
msgstr "%s"

#: storage/bootloader.py:302 storage/bootloader.py:306
msgid "Windows"
msgstr "Windows"

#: storage/devicetree.py:1569
msgid "This partition is part of an inconsistent LVM Volume Group."
msgstr "Ez a partíció egy inkonzisztens LVM része."

#: storage/library/lvm.py:265
#, python-format
msgid "vginfo failed for %s"
msgstr "%s - vginfo nem sikerült"

#: storage/library/lvm.py:291
#, python-format
msgid "lvs failed for %s"
msgstr "%s - lvs nem sikerült"

#: storage/formats/disklabel.py:28
#, fuzzy
msgid "partition table"
msgstr "Partíció"

#: storage/formats/raidmember.py:21
msgid "software RAID"
msgstr ""

#: storage/formats/physicalvolume.py:19
#, fuzzy
msgid "physical volume (LVM)"
msgstr "Fizikai kötet"

#: storage/formats/dmraidmember.py:19
msgid "dm-raid member device"
msgstr ""

#: storage/formats/filesystem.py:228
#, python-format
msgid "Unknown return code: %d."
msgstr "Ismeretlen visszatérési érték: %d"

#: storage/formats/filesystem.py:247
#, fuzzy, python-format
msgid "Migrating %s filesystem on %s"
msgstr "Fájlrendszer átméretezése %s eszközön"

#: storage/formats/filesystem.py:299
#, python-format
msgid "Creating %(type)s filesystem on %(device)s"
msgstr "%(type)s fájlrendszer létrehozása %(device)s eszközön"

#: storage/formats/filesystem.py:347
#, python-format
msgid "Resizing filesystem on %s"
msgstr "Fájlrendszer átméretezése %s eszközön"

#: storage/formats/filesystem.py:378
#, python-format
msgid "Checking filesystem on %s"
msgstr "Fájlrendszer ellenőrzése %s eszközön"

#: storage/formats/filesystem.py:387
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr "%(device)s eszközön %(type)s fájlrendszer ellenőrzési hiba: "

#: storage/formats/filesystem.py:391
#, fuzzy
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair. Restart installation after you have "
"corrected the problems on the filesystem."
msgstr ""
"Az ilyen hibák rendszerint azt jelentik, hogy probléma van a\n"
" fájlrendszerrel, ami felhasználói javítást igényel.\n"
" Indítsa újra\n"
"a telepítést a fájlrendszerhibák kijavítása után."

#: storage/formats/filesystem.py:397
msgid "Unrecoverable Error"
msgstr "Helyrehozhatatlan hiba"

#: storage/formats/filesystem.py:691
msgid "File system errors left uncorrected."
msgstr "Kijavítatlan fájlrendszerhibák."

#: storage/formats/filesystem.py:692
msgid "Operational error."
msgstr "Működési hiba."

#: storage/formats/filesystem.py:693
msgid "Usage or syntax error."
msgstr "Felhasználási vagy szintaktikai hiba."

#: storage/formats/filesystem.py:694
msgid "e2fsck cancelled by user request."
msgstr "e2fsck felhasználó által megszakítva"

#: storage/formats/filesystem.py:695
msgid "Shared library error."
msgstr "Megosztott függvénykönyvtár hiba (library error)."

#: storage/formats/filesystem.py:855
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""
"Javítható hibát észleltünk, vagy a dosfsck belső inkonzisztenciát észlelt."

#: storage/formats/filesystem.py:857
msgid "Usage error."
msgstr "Felhasználási hiba."

#: storage/partitioning.py:703
msgid "requested size exceeds maximum allowed"
msgstr ""

#: storage/partitioning.py:911
#, python-format
msgid "partition is too %(problem)s for %(format)s formatting"
msgstr ""

#: storage/partitioning.py:1051
#, fuzzy
msgid "not enough free space on disks"
msgstr "Nincs elég szabad terület"

#: storage/partitioning.py:1072
msgid "not enough free space after creating extended partition"
msgstr ""

#: storage/partitioning.py:1248
#, fuzzy
msgid "not enough space for LVM requests"
msgstr "Nincs elég szabad terület"

#: storage/partitioning.py:1645
msgid ""
"Could not find enough free space for automatic\n"
"partitioning, please use another partitioning method."
msgstr ""
"Az automatikus partícionálás végrehajtásához nem\n"
"található elegendő szabad terület, válasszon másik módot."

#: storage/partitioning.py:1669
msgid "Warnings During Automatic Partitioning"
msgstr "Partícionálási figyelmeztetések"

#: storage/partitioning.py:1670
#, python-format
msgid ""
"Following warnings occurred during automatic partitioning:\n"
"\n"
"%s"
msgstr ""
"Az automatikus particionálási művelet a következő\n"
"figyelmeztetéseket adta:\n"
"%s"

#: storage/partitioning.py:1679 storage/partitioning.py:1699
msgid ""
"\n"
"\n"
"Press 'OK' to exit the installer."
msgstr ""
"\n"
"\n"
"Nyomja meg az OK gombot a kilépéshez."

#: storage/partitioning.py:1681
#, python-format
msgid ""
"Could not allocate requested partitions: \n"
"%(msg)s.%(extra)s"
msgstr ""
"Ez a partíció nem beállítható: \n"
"%(msg)s.%(extra)s"

#: storage/partitioning.py:1700
msgid "Automatic Partitioning Errors"
msgstr "Automatikus partícionálási hibák"

#: storage/partitioning.py:1701
#, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"This can happen if there is not enough space on your hard drive(s) for the "
"installation. %(extra)s"
msgstr ""
"A particionálás alatt az alábbi hibák merültek fel:\n"
"\n"
"%(errortxt)s\n"
"\n"
"Ez akkor történhet, ha nincs elég szabad hely a merevlemezen. %(extra)s"

#: storage/devices/filedevice.py:93
#, python-format
msgid "Creating file %s"
msgstr "%s fájl létrehozása"

#: storage/devices/partition.py:369 storage/devices/raidarray.py:422
#: storage/devices/logicalvolume.py:217 storage/devices/volumegroup.py:245
#, python-format
msgid "Creating device %s"
msgstr "%s eszköz létrehozása"

#: storage/devices/volumegroup.py:217
msgid "device has not been created"
msgstr ""

#: storage/devices/volumegroup.py:223
msgid "cannot activate VG with missing PV(s)"
msgstr ""

#: storage/storageBackendHelpers.py:18
msgid "Please enter a volume group name."
msgstr "Adjon meg egy VG nevet."

#: storage/storageBackendHelpers.py:22
msgid "Volume Group Names must be less than 128 characters"
msgstr "A VG név hossza maximum 128 karakter"

#: storage/storageBackendHelpers.py:25
#, python-format
msgid "Error - the volume group name %s is not valid."
msgstr "Hiba - %s VG név nem megfelelő"

#: storage/storageBackendHelpers.py:30
msgid ""
"Error - the volume group name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"Hiba - a VG név érvénytelen karaktert vagy szóközt tartalmaz. Érvényes "
"karakterek: betűk, számok, '.' és '_'."

#: storage/storageBackendHelpers.py:40
msgid "Please enter a logical volume name."
msgstr "Adjon meg egy logikai kötet nevet."

#: storage/storageBackendHelpers.py:44
msgid "Logical Volume Names must be less than 128 characters"
msgstr "A logikai kötet neve nem lehet 128 karakternél hosszabb."

#: storage/storageBackendHelpers.py:48
#, python-format
msgid "Error - the logical volume name %s is not valid."
msgstr "Hiba - %s logikai kötetnév nem megfelelő"

#: storage/storageBackendHelpers.py:54
msgid ""
"Error - the logical volume name contains illegal characters or spaces.  "
"Acceptable characters are letters, digits, '.' or '_'."
msgstr ""
"Hiba - a logikai kötetnév érvénytelen karaktert vagy szóközt tartalmaz. "
"Érvényes karakterek: betűk, számok, '.' és '_'."

#: storage/storageBackendHelpers.py:68
msgid "Format as Swap?"
msgstr "Formázás lapozóterületként?"

#: storage/storageBackendHelpers.py:69
#, python-format
msgid ""
"%s has a partition type of 0x82 (Linux swap) but does not appear to be "
"formatted as a Linux swap partition.\n"
"\n"
"Would you like to format this partition as a swap partition?"
msgstr ""
"%s partíció típusa linux lapozóterület (0x82), de nincs lapozóterületként "
"megformázva.\n"
"\n"
"Meg akarja formázni lapozóterületként?"

#: storage/storageBackendHelpers.py:89
#, python-format
msgid "You are about to delete all partitions on the device '%s'."
msgstr "A '%s' eszköz minden partícióját készül törölni."

#: storage/storageBackendHelpers.py:139
msgid "Notice"
msgstr "Figyelem"

#: storage/storageBackendHelpers.py:140
#, python-format
msgid ""
"The following partitions were not deleted because they are in use:\n"
"\n"
"%s"
msgstr ""
"A következő partíciók nem kerülnek törlésre, mert használatban vannak:\n"
"\n"
"%s"

#: storage/storageBackendHelpers.py:154 storage/storageBackendHelpers.py:161
msgid "Unable To Delete"
msgstr "Nem törölhető"

#: storage/storageBackendHelpers.py:155
msgid "You must first select a partition to delete."
msgstr "Először válassza kia törlendő partíciót. "

#: storage/storageBackendHelpers.py:200
#, python-format
msgid ""
"The mount point %s is invalid.  Mount points must start with '/' and cannot "
"end with '/', and must contain printable characters and no spaces."
msgstr ""
"A %s csatolási pont érvénytelen. A csatolási pontoknak '/'-rel kell "
"kezdődniük, és sohasem végződhetnek '/'-el, csak nyomtatható karaktert "
"tartalmazhat szóköz nélkül."

#: storage/storageBackendHelpers.py:209
msgid "Error with Partitioning"
msgstr "Partícionálási hiba"

#: storage/storageBackendHelpers.py:210
#, python-format
msgid ""
"The following critical errors exist with your requested partitioning scheme. "
"These errors must be corrected prior to continuing with your install of "
"%(productName)s.\n"
"\n"
"%(errorstr)s"
msgstr ""
"Az alábbi kritikus hibák léptek föl a partícionálási sémában. A "
"%(productName)s telepítésének folytatásához ezeket a hibákat ki kell "
"javítani. \n"
"\n"
"%(errorstr)s"

#: storage/storageBackendHelpers.py:226
msgid "Partitioning Warning"
msgstr "Partícionálási figyelmeztetések"

#: storage/storageBackendHelpers.py:227
#, python-format
msgid ""
"The following warnings exist with your requested partition scheme.\n"
"\n"
"%s\n"
"\n"
"Would you like to continue with your requested partitioning scheme?"
msgstr ""
"A kiválasztott partícionálási sémában a következő figyelmeztetések léptek "
"fel.\n"
"\n"
"%s\n"
"\n"
"Kívánja folytatni így?"

#: storage/storageBackendHelpers.py:242
msgid ""
"The following pre-existing partitions have been selected to be formatted, "
"destroying all data."
msgstr ""
"Az alábbi már létező partíciók lettek megjelölve formázásra,\n"
"minden adat törlődni fog róluk."

#: storage/storageBackendHelpers.py:245
msgid ""
"Select 'Yes' to continue and format these partitions, or 'No' to go back and "
"change these settings."
msgstr ""
"Válassza az 'Igen'-t a partíciók formázásához, vagy a 'Nem'-et a "
"visszalépéshez és a beállítások megváltoztatásához."

#: storage/storageBackendHelpers.py:251
msgid "Format Warning"
msgstr "Formázási figyelmeztetés"

#: storage/storageBackendHelpers.py:279
#, python-format
msgid ""
"You are about to delete the volume group \"%s\".\n"
"\n"
"ALL logical volumes in this volume group will be lost!"
msgstr ""
"A \"%s\" VG-t készül törölni.\n"
"\n"
"A csoportban az összes logikai kötet el fog veszni!"

#: storage/storageBackendHelpers.py:283
#, python-format
msgid "You are about to delete the logical volume \"%s\"."
msgstr "Biztosan törli a \"%s\" logikai kötetet?"

#: storage/storageBackendHelpers.py:286
msgid "You are about to delete a RAID device."
msgstr "RAID eszközt készül törölni."

#: storage/storageBackendHelpers.py:288
#, python-format
msgid "You are about to delete the %s partition."
msgstr "A %s partíciót készül törölni."

#: storage/storageBackendHelpers.py:292
#, python-format
msgid "You are about to delete the %(type)s %(name)s"
msgstr "Törölni készül ezt: %(type)s %(name)s"

#: storage/storageBackendHelpers.py:302
msgid "Confirm Reset"
msgstr "Visszaállítás jóváhagyása"

#: storage/storageBackendHelpers.py:302
msgid ""
"Are you sure you want to reset the partition table to its original state?"
msgstr "Biztosan visszaállítja a partíciós táblát az eredeti állapotába?"

#: storage/storageBackendHelpers.py:310
msgid ""
"You have chosen to use a pre-existing partition for this\n"
"installation without formatting it. We recommend that you format\n"
"this partition to make sure files from a previous operating system\n"
"installation do not cause problems with this installation of Linux.\n"
"However, if this partition contains files that you need to keep,\n"
"such as home directories, then continue without formatting this\n"
"npartition."
msgstr ""
"Egy már létező partíciót választott a telepítéshez formázás nélkül.\n"
"Javasoljuk, hogy formázza meg, így elkerülhető, hogy az előző operációs\n"
"rendszer fájljai zavart okozzanak ezzel a linux telepítéssel.\n"
"Azonban ha a partíció olyan fájlokat tartalmaz, amit meg kell őriznie, "
"folytassa formázás nélkül."

#: storage/storageBackendHelpers.py:318
msgid "Format?"
msgstr "Formázás?"

#: storage/storageBackendHelpers.py:319
msgid "Do Not Format"
msgstr "Nincs formázás"

#: storage/storageBackendHelpers.py:326
#, python-format
msgid ""
"Partitions of type '%s' must be constrained to a\n"
"single drive.  To do this, select the drive in the 'Allowable Drives'\n"
"checklist."
msgstr ""
"A '%s' típusú partíciók egyetlen meghajtóra korlátozódnak.\n"
"Válasszon egyet a 'Megengedett meghajtók' listáról."

#: storage/storageBackendHelpers.py:331 storage/storageBackendHelpers.py:356
#: storage/storageBackendHelpers.py:376
#, fuzzy
msgid "Storage Device Warning"
msgstr "Tárolóeszközök inicializálása..."

#: storage/storageBackendHelpers.py:332
#, python-format
msgid ""
"The following storage device may contain recoverable data:<br><br>"
"%(description)s (%(size)s MB)<br><br>This device may have data that will be "
"<b>permanently lost</b> if you include it in this installation.<br><br>If "
"you don't care about any data on this device, choose <b>Reset device</b> to "
"include it in the installation process.<br><br>If you don't want the device "
"to be permanently erased, select <b>Ignore device</b> and the device will "
"not be considered as a possible installation target."
msgstr ""

#: storage/storageBackendHelpers.py:343
#, fuzzy
msgid "Reset device"
msgstr "Eszköz átméretezési hiba"

#: storage/storageBackendHelpers.py:343
#, fuzzy
msgid "Ignore device"
msgstr "Mellőzés"

#: storage/storageBackendHelpers.py:357
#, fuzzy, python-format
msgid ""
"There is inconsistent LVM data on %(msg)s. You can reinitialize all related "
"PVs (%(pvs)s) which will erase the LVM metadata, or ignore which will "
"preserve thecontents.This action may also be applied to all other PVs with "
"inconsistent metadata."
msgstr ""
"Hiba az LVM feldolgozása közben.\n"
"Az LVM inkonzisztens adatokat tartalmaz ezen: %(msg)s. Újrainicializálhatja\n"
" a vonatkozó köteteket (%(pvs)s), amivel az LVM metaadata törlődik, vagy\n"
" mellőzheti, amivel megmarad a tartalma. A művelet az összes többi\n"
" inkonzisztens metaadatot tartalmazó kötetre is kiterjeszthető."

#: storage/storageBackendHelpers.py:364
#, fuzzy
msgid "Yes, re-initialize"
msgstr "Újrainicializálás"

#: storage/storageBackendHelpers.py:364
msgid "No, protect data"
msgstr ""

#: storage/storageBackendHelpers.py:377
#, python-format
msgid ""
"Disk contains %(members_count)s BIOS RAID metadata, but is not part of any "
"recognized BIOS RAID sets. Ignoring disk %(members)s."
msgstr ""
"A lemez %(members_count)s BIOS RAID metaadatot tartalmaz, de egyik sem tagja "
"felismert BIOS RAID készletnek. %(members)s lemez figyelmen kívül hagyva."

#: storage/__init__.py:48
#, python-format
msgid "Failed teardownAll in storage.complete with error:%s"
msgstr "A storage.complete-ben a teardownAll meghiúsult. Hiba: %s"

#: storage/__init__.py:57
#, fuzzy
msgid "Storage Device Error"
msgstr "Tárolóeszközök inicializálása..."

#: storage/__init__.py:58
#, fuzzy, python-format
msgid "There was an error encountered while partitioning on device %s."
msgstr "Hiba történt a %s eszköz átméretezése közben."

#: storage/__init__.py:63
msgid "Storage Format Error"
msgstr ""

#: storage/__init__.py:64
#, fuzzy, python-format
msgid "There was an error encountered while formatting on device %s."
msgstr "Hiba történt a %s eszköz átméretezése közben."

#: storage/__init__.py:75
#, fuzzy
msgid "Ignore"
msgstr "Mindegyik mellőzése"

#: storage/__init__.py:158 storage/__init__.py:168
#, fuzzy
msgid "Dirty File Systems"
msgstr "Fájlrendszer"

#: storage/__init__.py:159
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Please boot your Linux installation, let the file systems be "
"checked and shut down cleanly to rescue.\n"
"%s"
msgstr ""

#: storage/__init__.py:169
#, python-format
msgid ""
"The following file systems for your Linux system were not unmounted "
"cleanly.  Would you like to mount them anyway?\n"
"%s"
msgstr ""

#: storage/__init__.py:336
msgid "This partition is holding the data for the hard drive install."
msgstr "Ez a partíció tartalmazza a merevlemezes telepítés adatait."

#: storage/__init__.py:339
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "Nem törölhet olyan LDL partíciót, amely DASD formázású."

#: storage/__init__.py:345
#, python-format
msgid ""
"This device is part of the RAID device %s, you have to edit or remove the "
"raid partition appropriately!"
msgstr ""
"Ez az eszköz a %s RAID eszköz része, változtassa meg a RAID beállításokat, "
"vagy távolítsa el a raid partíciót!"

#: storage/__init__.py:350
msgid "This device is part of a RAID device."
msgstr "Ez az eszköz egy RAID része."

#: storage/__init__.py:355
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "Ez az eszköz a '%s' LVM része."

#: storage/__init__.py:358
msgid "This device is part of a LVM volume group."
msgstr "Ez az eszköz egy LVM része."

#: storage/__init__.py:367
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""
"Ez az eszköz egy kiterjesztett partíció, amely nem törölhető logikai "
"partíciókat tartalmaz:\n"
"\n"

#: storage/__init__.py:873
#, fuzzy, python-format
msgid ""
"You have not defined a root partition (/),which is required for installation "
"of %s to continue."
msgstr ""
"Nem adott meg rendszer partíciót (/), amely szükséges a %s telepítéséhez\n"
"a folytatáshoz."

#: storage/__init__.py:878
#, fuzzy, python-format
msgid ""
"Your / partition is less than %(min)s MB which is lower than recommended for "
"a normal %(productName)s install."
msgstr ""
"A / partíció kisebb mint %(min)s MB, ami a javasolt legkisebb\n"
"meret a %(productName)s telepítéséhez."

#: storage/__init__.py:884
#, fuzzy, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"A %(mount)s partíció kisebb mint %(size)s MB, ami a javasolt legkisebb\n"
"meret a %(productName)s telepítéséhez."

#: storage/__init__.py:893
#, fuzzy
msgid ""
"You have not specified a swap partition. Due to the amount of memory "
"present, a swap partition is required to complete installation."
msgstr ""
"Nem adott meg lapozóterületet. A jelenleg használható memória esetén "
"lapozóterület szükséges a telepítés sikeres befejezéséhez."

#: storage/__init__.py:896
#, fuzzy
msgid ""
"You have not specified a swap partition. Although not strictly required in "
"all cases, it will significantly improve performancefor most installations."
msgstr ""
"Nem adott meg lapozóterületet. Habár nem minden esetben\n"
"elengedhetetlenül, a legtöbbször jelentősen megnöveli a rendszer\n"
"teljesítményét."

#: storage/__init__.py:902
#, python-format
msgid ""
"This mount point is invalid. The %s directory must be on the / file system."
msgstr ""
"Ez a csatolási pont érvénytelen. A %s könyvtárnak a / fájlrendszeren kell "
"lennie."

#: storage/__init__.py:905
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "A %s csatolási pontnak linux fájlrendszeren kell lennie."

#: storage/__init__.py:925
msgid "No Drives Found"
msgstr "Nem található meghajtó"

#: storage/__init__.py:926
msgid ""
"An error has occurred - no valid devices were found on\n"
"which to create new file systems. Please check your\n"
"hardware for the cause of this problem."
msgstr ""
"Hiba történt - nem található a rendszerben\n"
"új fájlrendszer létrehozására alkalmas érvényes eszköz.\n"
"Ellenőrizze a hardvereket a probléma okának megtalálásáért."
